name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.AWS_PORT }}

          script: |

            set -e

            cd /var/www/laravel-app

            echo "🔧 Fix permissions BEFORE composer"
            sudo chown -R www-data:www-data /var/www/laravel-app
            sudo chmod -R 775 storage bootstrap/cache

            echo "📥 Pulling latest code"
            git pull origin main

            echo "📦 Installing dependencies"
            composer install --no-dev --optimize-autoloader

            npm install
            npm run build

            echo "🧹 Clearing cache"
            php artisan optimize:clear

            echo "🗄 Running migrations"
            php artisan migrate --force

            echo "⚡ Rebuilding cache"
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "♻️ Restart queue"
            # php artisan queue:restart

            echo "✅ Deploy success"
