name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.AWS_PORT }}

          script: |

            set -e

            cd /var/www/laravel-app

            git config --global --add safe.directory /var/www/laravel-app

            echo "📥 Pulling latest code"
            git pull origin main

            echo "📦 Composer install"
            composer install --no-dev --optimize-autoloader

            echo "📦 Node build"
            npm install
            npm run build

            echo "🧹 Clearing cache"
            php artisan optimize:clear

            echo "🗄 Migrate"
            php artisan migrate --force

            echo "⚡ Cache rebuild"
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "🔐 Fix permissions"
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            echo "✅ Deploy success"
